### ISSUE TITLE
Grammar railroad diagram

### ISSUE THREAD

**Issue by mingodad** [joelspadin/tree-sitter-devicetree#7]
Using this page https://meimporta.eu/tree-sitter/json2ebnf.html we can get a navigable railroad diagram for tree-sitter grammars like this project.

See also https://github.com/tree-sitter/tree-sitter/issues/2268 .

Cheers !

**Comment by joelspadin** [comment]
This is interesting, but I'm not sure why you filed an issue. Is there a change to this repo you'd like to incorporate?

**Comment by mingodad** [comment]
Not really it's mainly to spread the knowledge of railroad diagrams as a tool to help document/debug/develop a grammar.
